use serde_json::Value;
use std::fs;

mod common;
use common::*;

/// Verify Rust token counts match Go's cl100k_base BPE counts exactly.
///
/// Before this change Rust used a bytes/4 heuristic; Go used the real
/// cl100k_base encoder (pkoukk/tiktoken-go).  The expected counts below were
/// verified against the Go binary:
///   go run tok_check.go  =>  src/app.go: 11, src/helper.go: 14
///
/// This test is the primary proof that the ctx-tokens port achieves count parity.
#[test]
fn pack_json_token_counts_match_go_cl100k_base() {
    let root = test_dir("token-parity");
    fs::create_dir_all(root.join("src")).unwrap();
    // cl100k_base count: 11
    fs::write(
        root.join("src/app.go"),
        "package src\n\nfunc Run() {\n    Helper()\n}\n",
    )
    .unwrap();
    // cl100k_base count: 14
    fs::write(
        root.join("src/helper.go"),
        "package src\n\nfunc Helper() string {\n    return \"ok\"\n}\n",
    )
    .unwrap();

    let args = [
        "pack",
        "--no-contract",
        "--format",
        "json",
        "--goal",
        "run helper",
        "--budget",
        "10000",
    ];

    // Verify Rust token counts against the Go oracle independently.
    let go_output = run_go_in(&root, &args);
    let rust_output = run_rust_in(&root, &args);

    let go_payload: Value = serde_json::from_slice(&go_output.stdout).unwrap_or_else(|err| {
        panic!(
            "parse Go pack JSON: {err}\n{}",
            String::from_utf8_lossy(&go_output.stdout)
        )
    });
    let rust_payload: Value = serde_json::from_slice(&rust_output.stdout).unwrap_or_else(|err| {
        panic!(
            "parse Rust pack JSON: {err}\n{}",
            String::from_utf8_lossy(&rust_output.stdout)
        )
    });

    // Extract per-file token counts from both sides and assert equality.
    for filename in ["src/app.go", "src/helper.go"] {
        let go_tokens = go_payload["included"]
            .as_array()
            .and_then(|items| items.iter().find(|item| item["path"] == filename))
            .and_then(|item| item["tokens"].as_i64())
            .unwrap_or_else(|| panic!("Go output missing tokens for {filename}"));
        let rust_tokens = rust_payload["included"]
            .as_array()
            .and_then(|items| items.iter().find(|item| item["path"] == filename))
            .and_then(|item| item["tokens"].as_i64())
            .unwrap_or_else(|| panic!("Rust output missing tokens for {filename}"));

        assert_eq!(
            rust_tokens, go_tokens,
            "token count mismatch for {filename}: Rust={rust_tokens} Go={go_tokens}"
        );
    }

    // Also assert the absolute tiktoken counts so a regression is immediately visible.
    // Counts verified: go run tok_check.go (pkoukk/tiktoken-go cl100k_base)
    let rust_included = rust_payload["included"].as_array().expect("included array");
    let app = rust_included
        .iter()
        .find(|item| item["path"] == "src/app.go")
        .expect("src/app.go in Rust included");
    let helper = rust_included
        .iter()
        .find(|item| item["path"] == "src/helper.go")
        .expect("src/helper.go in Rust included");
    assert_eq!(
        app["tokens"].as_i64().unwrap(),
        11,
        "src/app.go: expected 11 cl100k_base tokens"
    );
    assert_eq!(
        helper["tokens"].as_i64().unwrap(),
        14,
        "src/helper.go: expected 14 cl100k_base tokens"
    );
}

// ── Wave-1 byte-parity suite for `noise` ──────────────────────────────────────
//
// Goal: prove `noise` is byte-identical to Go across its entire flag/value
// surface so it is ready for Wave-3 zero-delegation cutover.
//
// Go surface (internal/cli/noise.go):
//   Flags: --top N (default 20), --apply (bool), --format text|json
//   Positional: optional root path (MaximumNArgs(1))
//   Formats: text (default), json
//   --apply: emits a gitignore-syntax proposal grouped by reason.
//     - Glob aggregation: 3+ same-dir+ext files collapsed to dir/*.ext
//     - Groups ordered: generated > lockfile > testdata > binary > huge-json > low-density
//     - Header line uses em dash (—), not hyphen
//   NOTE: --apply output contains `# Generated by ... on YYYY-MM-DD`.
//   The date is the current UTC date — both binaries run at the same time,
//   so the date portion matches. Not a stability risk.
//   NOTE: --noise-engine {rust} carve-out: Go exits 1; Rust native. Not tested.
//
// Fixtures: minimal directories with controlled noise file types.
//   Shared: go.sum (lockfile), app.min.js (generated), keep.go (clean)
//   Glob: 3× *.min.js in a src/ dir to exercise aggregation
//
// No `return None` in run_noise_command reachable by valid invocation:
//   parse_noise_args returns None only for unknown flags or >1 positional —
//   both are error paths. All valid invocations reach Some(NoiseArgs).
