// crates/ctx-contract/src/embed.rs
//
// Port of internal/contract/embed.go. The host-format markers (markdown
// HTML-comment, plain header, JSON top-level field) are kept identical
// so packs generated by either implementation parse cleanly on the
// other side.

use once_cell::sync::Lazy;
use regex::bytes::Regex as BytesRegex;
use serde_json::Value;
use std::collections::BTreeMap;
use std::io::{self, Write};

use crate::types::Contract;
use crate::SCHEMA_VERSION;

const MD_OPEN: &str = "<!-- ctx:contract v1";
const MD_CLOSE: &str = "-->";
const PLAIN_HEADER: &str = "# CTX-CONTRACT v1:";

/// Regex matching the embedded contract block in either host format.
/// Mirrors `contractBlockRe` in embed.go.
///
/// PARITY (Phase 1 C-01): Go's regexp treats `\s` as ASCII-only;
/// Rust's `regex` defaults to Unicode-aware classes. Wrap each `\s`
/// in `(?-u:\s)` so NBSP / ideographic space don't match here.
static CONTRACT_BLOCK_RE: Lazy<BytesRegex> = Lazy::new(|| {
    BytesRegex::new(
        r"(?s)(?:<!-- ctx:contract v1(?-u:\s)*(.*?)(?-u:\s)*-->|# CTX-CONTRACT v1:(?-u:\s)*(\{.*?\})(?-u:\s)*(?:\n|$))",
    )
    .expect("compile contractBlockRe")
});

/// Serialises the contract as a `serde_json::Value`, suitable for
/// splicing into a packJSON map under the `"contract"` key.
pub fn to_json_field(c: &Contract) -> io::Result<Value> {
    serde_json::to_value(c).map_err(io::Error::other)
}

/// EmbedMarkdown writes the contract block in HTML-comment form, with a
/// pretty-printed JSON body so a human can inspect it.
pub fn embed_markdown<W: Write + ?Sized>(w: &mut W, c: &Contract) -> io::Result<()> {
    let body = serde_json::to_string_pretty(c).map_err(io::Error::other)?;
    write!(w, "\n{}\n{}\n{}\n", MD_OPEN, body, MD_CLOSE)
}

/// EmbedXML aliases EmbedMarkdown — XML packs today are plain text
/// wrapped in a single root tag, so an HTML comment is the safest
/// place to attach the contract. Mirrors Go's implementation exactly.
pub fn embed_xml<W: Write + ?Sized>(w: &mut W, c: &Contract) -> io::Result<()> {
    embed_markdown(w, c)
}

/// EmbedPlain writes a single-line `# CTX-CONTRACT v1: {json}` header.
pub fn embed_plain<W: Write + ?Sized>(w: &mut W, c: &Contract) -> io::Result<()> {
    let body = serde_json::to_string(c).map_err(io::Error::other)?;
    write!(w, "\n{} {}\n", PLAIN_HEADER, body)
}

/// EmbedJSONPatch splices the contract into an already-JSON-encoded pack
/// body under the top-level `"contract"` key. If the body is not a JSON
/// object we fall back to appending a `EmbedPlain`-style block.
pub fn embed_json_patch(pack_json: &[u8], c: &Contract) -> io::Result<Vec<u8>> {
    let trimmed = trim_ascii_whitespace(pack_json);
    if trimmed.is_empty() || trimmed[0] != b'{' {
        let mut buf = pack_json.to_vec();
        embed_plain(&mut buf, c)?;
        return Ok(buf);
    }
    // PARITY (F-05): Go's `json.Marshal(map[string]json.RawMessage)`
    // always sorts map keys alphabetically. serde_json's `Map` (with the
    // `preserve_order` feature this crate enables for other call-sites)
    // uses insertion order, which would diverge on multi-key inputs.
    // Round-trip through `BTreeMap` to recover alphabetical ordering for
    // this one call.
    let mut doc: BTreeMap<String, Value> =
        serde_json::from_slice(trimmed).map_err(io::Error::other)?;
    let raw = to_json_field(c)?;
    doc.insert("contract".to_string(), raw);
    serde_json::to_vec(&doc).map_err(io::Error::other)
}

/// Reads the embedded contract block from a pack body. Tries the JSON
/// pack form first (top-level `"contract"` field), then falls back to
/// the regex path used by markdown / XML / plain packs.
pub fn parse_from_pack(pack_body: &[u8]) -> Option<Contract> {
    if let Some(c) = parse_from_json_pack(pack_body) {
        return Some(c);
    }
    let caps = CONTRACT_BLOCK_RE.captures(pack_body)?;
    // Group 1 = HTML-comment body, group 2 = plain header body.
    let raw: &[u8] = if let Some(m) = caps.get(1).filter(|m| !m.as_bytes().is_empty()) {
        m.as_bytes()
    } else if let Some(m) = caps.get(2).filter(|m| !m.as_bytes().is_empty()) {
        m.as_bytes()
    } else {
        return None;
    };
    let raw = trim_ascii_whitespace(raw);
    let start = raw.iter().position(|&b| b == b'{')?;
    let end = raw.iter().rposition(|&b| b == b'}')?;
    if end <= start {
        return None;
    }
    let mut c: Contract = serde_json::from_slice(&raw[start..=end]).ok()?;
    if c.schema_version == 0 {
        c.schema_version = SCHEMA_VERSION;
    }
    Some(c)
}

fn parse_from_json_pack(pack_body: &[u8]) -> Option<Contract> {
    let trimmed = trim_ascii_whitespace(pack_body);
    if trimmed.is_empty() || trimmed[0] != b'{' {
        return None;
    }
    let doc: serde_json::Map<String, Value> = serde_json::from_slice(trimmed).ok()?;
    let raw = doc.get("contract")?;
    // PARITY (F-03): Go decodes to `map[string]json.RawMessage` and
    // gates on `len(bytes.TrimSpace(raw)) == 0`. JSON `null` is four
    // bytes, not empty, so Go proceeds to `json.Unmarshal(rawNull, &c)`
    // which leaves `c` zero-valued, then SchemaVersion=0 → SchemaVersion=1.
    // serde_json's `from_value(Value::Null)` for a struct returns Err
    // (not "leave zero-valued"), so we explicitly treat null as a fresh
    // default Contract here to match Go's `(Contract{SchemaVersion:1}, true)`.
    let mut c: Contract = if raw.is_null() {
        Contract::default()
    } else {
        serde_json::from_value(raw.clone()).ok()?
    };
    if c.schema_version == 0 {
        c.schema_version = SCHEMA_VERSION;
    }
    Some(c)
}

/// Returns `pack_body` with the embedded contract section removed.
/// Idempotent when no block is present.
pub fn strip_contract_block(pack_body: &[u8]) -> Vec<u8> {
    let stripped = CONTRACT_BLOCK_RE.replace_all(pack_body, &b""[..]);
    let mut out = stripped.into_owned();
    while out.last() == Some(&b'\n') {
        out.pop();
    }
    out
}

fn trim_ascii_whitespace(b: &[u8]) -> &[u8] {
    let mut start = 0usize;
    let mut end = b.len();
    while start < end && b[start].is_ascii_whitespace() {
        start += 1;
    }
    while end > start && b[end - 1].is_ascii_whitespace() {
        end -= 1;
    }
    &b[start..end]
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::File;

    fn fixture_contract() -> Contract {
        Contract {
            schema_version: SCHEMA_VERSION,
            created: "2026-05-29T00:00:00Z".into(),
            files: vec![File {
                path: "a.go".into(),
                line_start: 1,
                line_end: 10,
                sha256: "abc".into(),
                line_hashes: vec![],
                symbols: vec!["A".into()],
            }],
        }
    }

    #[test]
    fn embed_and_parse_markdown_roundtrips() {
        let c = fixture_contract();
        let mut buf = Vec::new();
        embed_markdown(&mut buf, &c).unwrap();
        let parsed = parse_from_pack(&buf).unwrap();
        assert_eq!(parsed.schema_version, c.schema_version);
        assert_eq!(parsed.files[0].path, "a.go");
    }

    #[test]
    fn embed_and_parse_plain_roundtrips() {
        let c = fixture_contract();
        let mut buf = Vec::new();
        embed_plain(&mut buf, &c).unwrap();
        let parsed = parse_from_pack(&buf).unwrap();
        assert_eq!(parsed.schema_version, c.schema_version);
    }

    #[test]
    fn json_patch_adds_contract_field() {
        let c = fixture_contract();
        let patched = embed_json_patch(br#"{"pack":"placeholder"}"#, &c).unwrap();
        let parsed = parse_from_pack(&patched).unwrap();
        assert_eq!(parsed.schema_version, c.schema_version);
    }

    #[test]
    fn strip_removes_block() {
        let c = fixture_contract();
        let mut buf = Vec::from(&b"hello\n"[..]);
        embed_markdown(&mut buf, &c).unwrap();
        let stripped = strip_contract_block(&buf);
        assert_eq!(stripped, b"hello");
    }
}
